Core/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = "Core"

urlpatterns = [
    # path("", views.homepage, name = "homepage"),
    path("", views.index, name = "index"),
    path("login/", views.loginView, name = "login"),
    path("logout/", views.logoutView, name = "logout"),
    path("create-account/", views.createAccount, name = "createAccount"),
    # path("create-student/", views.createStudent, name = "createStudent"),
    path("admin-panel/", views.adminPanel, name = "adminPanel"),
    # path("admin-panel/delete-student/<str:username>/", views.deleteStudent, name = "deleteStudent"),
    path("student-panel/", views.studentPanel, name = "studentPanel"),
    #path("course-description/", views.courseDescription, name = "courseDescription"),
    path("fetch-courses/", views.fetchCourses, name = "fetchCourses"),
    path("fetch-faculties/", views.fetchFaculties, name = "fetchFaculties"),
    path("fetch-students/", views.fetchStudents, name = "fetchStudents"),
    path("delete-courses/",views.deleteCourses, name="deleteCourses"),
    path("filter-courses/",views.filterCourses,name="filterCourses"),
    path("insert-course-admin/",views.insertCourseAdmin,name="insertCourseAdmin"),
    path("delete-course-admin/",views.deleteCourseAdmin,name="deleteCourseAdmin"),
    path("set-isLive-1-admin/",views.setisLive1,name="setisLive1"),
    path("set-isLive-0-admin/",views.setisLive0,name="setisLive0"),
    path('getAllCourses/',views.getAllCourses,name='getAllCourses'),
    #path("<course_courseName>/",views.courseDescription,name="courseDescription"),
    path("updateCap/",views.updateCap,name="updateCap"),
]

urlpatterns += static(
    settings.MEDIA_URL, 
    document_root = settings.MEDIA_ROOT
)

haveASeat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Core.urls")),
]

Core/models.py
from django.db import models
from django.contrib.auth.models import User

class Branch(models.Model):
    branchName = models.CharField(max_length = 100)

    class Meta:
        verbose_name = "Branch"
        verbose_name_plural = "Branches"

    def __str__(self):
        return self.branchName

class UserRole(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    role = models.CharField(max_length = 50)

    class Meta:
        verbose_name = "UserRole"
        verbose_name_plural = "UserRoles"

class Department(models.Model):
    departmentName = models.CharField(max_length = 100)

    class Meta:
        verbose_name = "Department"
        verbose_name_plural = "Departments"

    def __str__(self):
        return self.departmentName

class Admin(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    profilePicture = models.ImageField(upload_to = "Profile Pictures/Admins/")
    program = models.CharField(max_length = 50)    

    class Meta:
        verbose_name = "Admin"
        verbose_name_plural = "Admins"

class Student(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    rollNumber = models.IntegerField(unique = True)
    dateOfJoining = models.DateField(auto_now = True)
    graduationYear = models.IntegerField(null = False, blank = False)
    profilePicture = models.ImageField(upload_to = "Profile Pictures/Students/")
    batch = models.CharField(max_length = 50)
    program = models.CharField(max_length = 50)
    branch = models.ForeignKey(Branch, on_delete = models.SET_NULL, null = True, blank = True)

    class Meta:
        verbose_name = "Student"
        verbose_name_plural = "Students"

class DOAA(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    profilePicture = models.ImageField(upload_to = "Profile Pictures/DOAA/")

    class Meta:
        verbose_name = "DOAA"
        verbose_name_plural = "DOAA"

class Faculty(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    profilePicture = models.ImageField(upload_to = "Profile Pictures/Faculties/")
    profileLink = models.URLField()

    class Meta:
        verbose_name = "Faculty"
        verbose_name_plural = "Faculties"

class Course(models.Model):
    section = models.CharField(max_length = 1)
    courseName = models.CharField(max_length = 50)
    credits = models.IntegerField(default = 0)
    studentCap = models.IntegerField(default = 0)
    courseDescription = models.TextField()
    program = models.CharField(max_length = 50)
    department = models.ForeignKey(Department, on_delete = models.SET_NULL, null = True)
    isLive = models.IntegerField(default = 0)

class CourseFaculty(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete = models.CASCADE, related_name = "teaches")
    course = models.ForeignKey(Course, on_delete = models.CASCADE, related_name = "taughtBy")    

    class Meta:
        verbose_name = "CourseFaculty"
        verbose_name_plural = "CourseFaculties"

class Announcement(models.Model):
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null = True)
    timeStamp = models.DateTimeField(auto_now = True)
    content = models.CharField(max_length = 500)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    timeStamp = models.DateTimeField(auto_now = True)
    content = models.CharField(max_length = 500)
    parentComment = models.ForeignKey("Comment", related_name = "parentOf", on_delete = models.SET_NULL, null = True)

class PreReq(models.Model):
    course = models.ForeignKey(Course, on_delete = models.CASCADE, related_name = "preReqs")
    preReqCourse = models.ForeignKey(Course, on_delete = models.CASCADE, related_name = "preReqOf")

    class Meta:
        verbose_name = "PreReq"
        verbose_name_plural = "PreReqs"

class AntiReq(models.Model):
    course = models.ForeignKey(Course, on_delete = models.CASCADE, related_name = "antiReqs")
    antiReqCourse = models.ForeignKey(Course, on_delete = models.CASCADE, related_name = "antiReqOf")

    class Meta:
        verbose_name = "AntiReq"
        verbose_name_plural = "AntiReqs"

Core/views.py
import json
import datetime
from django.db import connection
from django.conf import settings
from django.shortcuts import render
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *

cursor = connection.cursor()

############################### sql queries using api #############################

# create queries

def createCourses():
     # creating an object
        courseobj = Course(1, 'A', 'Introduction To Programming', 4,100,'Introduction of Programming is the first programming course in the college curriculum, and aims to bridge the gap between students who have prior coding experience and those who have none. The main goal of this course is to prepare students to understand basic algorithms and data structures, write organized code, and to gain practical experience with debugging, compiling and running programs.', 'B-Tech', 1, 1)

        # object.save() executes the insert query into the database
        courseobj.save()

        courseobj1 = Course(2, 'B', 'Machine Learning', 4,200,'This is an introductory course on Machine Learning (ML) that is offered to undergraduate and graduate students. The contents are designed to cover both theoretical and practical aspects of several well-established ML techniques. The assignments will contain theory and programming questions that help strengthen the theoretical foundations as well as learn how to engineer ML solutions to work on simulated and publicly available real datasets. The project(s) will require students to develop a complete Machine Learning solution requiring preprocessing, design of the classifier/regressor, training and validation, testing and evaluation with quantitative performance comparisons.', 'B-Tech', 2, 0)

        courseobj1.save()

        courseobj2 = Course(3, 'A', 'Algorithm Design & Analysis', 4,120,'This is a follow-up course to DSA (Data Structures and Algorithms). The focus of this course in on the design of algorithms, proofs of correctness and methods to analyse resource requirements of their algorithms. Students learn fundamental algorithmic design paradigms such as greedy algorithms, dynamic programming, divide and conquer, etc. and also learn some more data structures. The later part of the course focuses on the limitations of algorithms. In particular, the theory of NP-completeness. Students are also required to design and implement algorithms using the techniques the learn.', 'B-Tech', 3, 0)

        courseobj2.save()

        courseobj3 = Course(4, 'B', 'Data Structures & Algorithms', 4,220,'This course is aimed at giving students a background in basic data structures and algorithms along with their impact in solving real life problems using a computer. The major focus will be on covering the basic data structures, b) Algorithm analysis using recurrence relations and c) problem solving using Java', 'B-Tech', 4, 0)

        courseobj3.save()

        courseobj4 = Course(5, 'A', 'Statistics', 4,100,'This course is aimed at giving students a background in basic data structures and algorithms along with their impact in solving real life problems using a computer. The major focus will be on covering the basic data structures, b) Algorithm analysis using recurrence relations and c) problem solving using Java', 'M-Tech', 3, 0)

        courseobj4.save()

        courseobj5 = Course(6, 'B', 'Genomic Algorithms', 2,50,'This course is aimed at giving students a background in basic data structures and algorithms along with their impact in solving real life problems using a computer. The major focus will be on covering the basic data structures, b) Algorithm analysis using recurrence relations and c) problem solving using Java', 'PhD', 1, 1)

        courseobj5.save()

        courseobj6 = Course(7, 'A', 'Iski Topi Uske Sir', 2,10,'This course is aimed at giving students a background in basic data structures and algorithms along with their impact in solving real life problems using a computer. The major focus will be on covering the basic data structures, b) Algorithm analysis using recurrence relations and c) problem solving using Java', 'M-Tech', 4, 1)

        courseobj6.save()

        courseList = [courseobj, courseobj1,courseobj2,courseobj3,courseobj4,courseobj5,courseobj6]

        return courseList

def createDepartment():
    dep1 = Department(1,"CSE")
    dep1.save()
    dep2 = Department(2,"ECE")
    dep2.save()
    dep3 = Department(3,"MTH")
    dep3.save()
    dep4 = Department(4,"SSH")
    dep4.save()

    dList = [dep1,dep2,dep3,dep4]
    return dList

####### calls for creating #####
depList = createDepartment()
######## global lists ##########
courseList = []

def createPreReq():
    pre1 = PreReq(1,2,1)
    pre1.save()
    pre2 = PreReq(2,2,5)
    pre2.save()
    pre3 = PreReq(3,3,1)
    pre3.save()
    pre4 = PreReq(4,3,4)
    pre4.save()
    pre5 = PreReq(5,4,1)
    pre5.save()

    preList = [pre1,pre2,pre3,pre4,pre5]
    return preList

######## for preReq ###########
# preReqList = createPreReq()

# insert course from admin panel
def insertCourseAdmin(request):
    if request.user.is_authenticated:
        username = request.user.username
        user = User.objects.get(username = username)
        role = UserRole.objects.get(user=user)
        if request.method == "POST" and role.role=='admin':
            department = Department.objects.get(departmentName = request.POST.get('department'))
            newCourse = Course(id = request.POST.get('id'), section = request.POST.get('section'), courseName = request.POST.get('courseName'), credits = request.POST.get('credits'), studentCap = request.POST.get('studentCap'), courseDescription = request.POST.get('courseDescription'), program = request.POST.get('program'), department = department, isLive = 0)
            newCourse.save()
            print("Saved")
        return HttpResponseRedirect("/"+role.role+"-panel")
    return HttpResponseRedirect("/")

######################################### Updation queries ##############################

# update studentCap in a Course from admin-panel
def updateCap(request):
    if request.user.is_authenticated:
        username = request.user.username
        user = User.objects.get(username = username)
        role = UserRole.objects.get(user=user)
        if request.method == "POST" and role.role=='admin':
            course = Course.objects.get(id = request.POST.get('id'))
            course.studentCap = request.POST.get('studentCap')
            course.save()
            print("Course cap is updated.")
        return HttpResponseRedirect("/"+role.role+"-panel")
    return HttpResponseRedirect("/")

# make isLive=1 courses
# make Course Live from Admin Panel
def setisLive1(request):
    if request.user.is_authenticated:
        username = request.user.username
        user = User.objects.get(username = username)
        role = UserRole.objects.get(user=user)
        if request.method == "POST" and role.role=='admin':
            course = Course.objects.get(id = request.POST.get('id'))
            course.isLive=1
            course.save()
            print("Course is live.")
        return HttpResponseRedirect("/"+role.role+"-panel")
    return HttpResponseRedirect("/")

# make isLive=0 courses
# make Course Inactive from Admin Panel
def setisLive0(request):
    if request.user.is_authenticated:
        username = request.user.username
        user = User.objects.get(username = username)
        role = UserRole.objects.get(user=user)
        if request.method == "POST" and role.role=='admin':
            course = Course.objects.get(id = request.POST.get('id'))
            course.isLive=0
            course.save()
            print("Course has been removed from live courses.")
        return HttpResponseRedirect("/"+role.role+"-panel")
    return HttpResponseRedirect("/")

# delete queries

# delete courses from student panel
def deleteCourses(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            # courseList = createCourses()
            snos = request.POST.getlist("courseList")
            print(snos)
            for i in snos:
                courseObject = Course.objects.filter(id=i)
                # print(courseObject[0].id)
                for course in courseList:
                    if len(courseObject) != 0 and course.id == courseObject[0].id:
                        print(course.id)
                        courseList.remove(course)
                
                courseObject.delete()

            context = {'courseList': courseList}
            return render(request, "student-panel.html", context)
    else:
        return HttpResponseRedirect("/")

# delete course from admin panel
def deleteCourseAdmin(request):
    if request.user.is_authenticated:
        username = request.user.username
        user = User.objects.get(username = username)
        role = UserRole.objects.get(user=user)
        if request.method == "POST" and role.role=='admin':
            course = Course.objects.get(id = request.POST.get('id'))
            course.delete()
            print("Deleted")
        return HttpResponseRedirect("/"+role.role+"-panel")
    return HttpResponseRedirect("/")


# read queries
def filterCourses(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            checkBtech = request.POST.get("B-Tech")
            checkMtech = request.POST.get("M-Tech")
            checkPhD = request.POST.get("PhD")
            
            # print(type(checkBtech))

            check4 = request.POST.get("cred4")
            check2 = request.POST.get("cred2")

            filteredCourses = []

            if checkBtech == None and checkMtech == None and checkPhD == None:
                querySet = Course.objects.filter(credits__in = [check4,check2])
            else:

Core/templates/add-student.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'CSS/create-student-style.css' %}">
    <title>haveASeat | Create a Student</title>
</head>
<body>
    <form id="Create-Student-Form" method="POST" action="{% url 'Core:createStudent' %}" enctype="multipart/form-data">
        <p id="Form-Heading">Create a Student</p>
        <label for="firstName" class="Create-Student-Form-Label">First Name</label>
        <input type="text" name="firstName" id="" class="Create-Student-Form-Field">
        <label for="lastName" class="Create-Student-Form-Label">Last Name</label>
        <input type="text" name="lastName" id="" class="Create-Student-Form-Field">
        <label for="email" class="Create-Student-Form-Label">Email</label>
        <input type="email" name="email" id="" class="Create-Student-Form-Field">
        <label for="username" class="Create-Student-Form-Label">Username</label>
        <input type="text" name="username" id="" class="Create-Student-Form-Field">
        <label for="password" class="Create-Student-Form-Label">Password</label>
        <input type="password" name="password" id="" class="Create-Student-Form-Field">
        <label for="rollNumber" class="Create-Student-Form-Label">Roll Number</label>
        <input type="text" name="rollNumber" id="" class="Create-Student-Form-Field">
        <label for="graduationYear" class="Create-Student-Form-Label">Graduation Year</label>
        <input type="text" name="graduationYear" id="" class="Create-Student-Form-Field">
        <label for="batch" class="Create-Student-Form-Label">Batch</label>
        <input type="text" name="batch" id="" class="Create-Student-Form-Field">
        <label for="program" class="Create-Student-Form-Label">Program</label>
        <select name="program" id="" class="Create-Student-Form-Field">
            <option value="B-Tech">B. Tech</option>
            <option value="M-Tech">M. Tech</option>
            <option value="PhD">PhD</option>
        </select>
        <label for="branch" class="Create-Student-Form-Label">Branch</label>
        <select name="branch" id="" class="Create-Student-Form-Field">
            <option value="CSE">CSE</option>
            <option value="ECE">ECE</option>
            <option value="CSB">CSB</option>
            <option value="CSD">CSD</option>
            <option value="CSAM">CSAM</option>
            <option value="CSSS">CSSS</option>
        </select>
        <label for="profilePicture" class="Create-Student-Form-Label">Profile Picture</label>
        <input type="file" name="profilePicture" accept="image/png" id="" class="Create-Student-Form-Field">
        {% csrf_token %}
        <input id="Create-Student-Form-Submit" type="submit" value="Create">
    </form>
</body>
</html>

Core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>haveASeat | {% block title %}{% endblock %}</title>
    <!-- Stylesheets -->
    {% block styles %}
    {% endblock %}

    <!-- JavaScript at the top -->
    {% block topJavaScript %}
    {% endblock %}
</head>
<body>
<!-- Body Content -->
{% block content %}
{% endblock %}

</body>
<!-- JavaScript at the bottom -->
{% block bottomJavaScript %}
{% endblock %}
</html>

Core/templates/course-description.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{% static 'CSS/courseDescription-style.css' %}"
    />
    <title>haveASeat | CSE101</title>
  </head>
  <body>
    <div class="Container">
      <div class="Left-Side-Panel">
        <div class="Section-Heading">
          <p>Course Registration</p>
        </div>
        <div class="Section-Heading">
          <p>
            <a href="#" style="text-decoration: none; color: white;"
              >Announcements</a
            >
          </p>
        </div>
      </div>
      <div class="Main-Panel">
        <div class="Panel-Secion"></div>
        <div class="Panel-Results">
          <table class="Panel-Table">
            <tr class="Panel-Table-Row">
              <th class="Panel-Table-Heading">Course Name</th>
              <td class="Panel-Table-Heading">{{course.courseName}}</td>
            </tr>
            <tr class="Panel-Table-Row">
              <th class="Panel-Table-Heading">Credits</th>
              <td class="Panel-Table-Heading">{{course.credits}}</td>
            </tr>
            <tr class="Panel-Table-Row">
              <th class="Panel-Table-Heading">Course Offered to</th>
              <td class="Panel-Table-Heading">{{course.program}}</td>
            </tr>
            <tr class="Panel-Table-Row">
              <th class="Panel-Table-Heading">Course Description</th>
              <td class="Panel-Table-Heading">{{course.courseDescription}}</td>
            </tr>
            <tr class="Panel-Table-Row">
              <th class="Panel-Table-Heading">Student Capacity</th>
              <td class="Panel-Table-Heading">{{course.studentCap}}</td>
            </tr>
            <tr class="Panel-Table-Row">
              <th class="Panel-Table-Heading">Department</th>
              <td class="Panel-Table-Heading">
                {{course.getDepartment}}
              </td>
            </tr>
            <tr class="Panel-Table-Row">
              <th class="Panel-Table-Heading">Pre-requisites</th>
              <td class="Panel-Table-Heading">
                <table class="Panel-Table">
                  {% for pre in preReq %}
                  <tr class="Panel-Table-Row">
                    <td class="Panel-Table-Heading">{{pre.courseName}}</td>
                  </tr>
                  {% endfor %}
                </table>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </body>
  <script src="{% static 'JavaScript/admin-script.js' %}"></script>
</html>

Core/templates/create-account.html
{% extends 'base.html' %}
{% load static %}

<!-- Title of the page -->
{% block title %}
Create an Account
{% endblock %}

<!-- Stylesheets -->
{% block styles %}
{% endblock %}

<!-- JavaScript at the top -->
{% block topJavaScript %}
{% endblock %}

<!-- Body Content -->
{% block content %}
<form action="{% url 'Core:createAccount' %}" method="POST" id="Create-Account-Form">
    <input type="text" name="username" id="Username" class="Input-Field" placeholder="Enter your username">
    <input type="email" name="email" id="Email" class="Input-Field" placeholder="Enter your email">
    <input type="password" name="password" id="Password" class="Input-Field" placeholder="Enter your password">
    <select name="role" id="role" class="Input-Field">
        <option value="admin">Admin</option>
        <option value="doaa">DOAA</option>
        <option value="faculty">Faculty</option>
        <option value="student">Student</option>
    </select>
    {% csrf_token %}
    <input type="submit" value="Log In">
</form>
<p>Already registered? <a href="{% url 'Core:login' %}">Log In</a></p>
{% endblock %}

<!-- JavaScript at the bottom -->
{% block bottomJavaScript %}
{% endblock %}

Core/templates/index.html
{% extends 'base.html' %}
{% load static %}

<!-- Title of the page -->
{% block title %}
Login
{% endblock %}

<!-- Stylesheets -->
{% block styles %}
{% endblock %}

<!-- JavaScript at the top -->
{% block topJavaScript %}
{% endblock %}

<!-- Body Content -->
{% block content %}
Hello World!
{% endblock %}

<!-- JavaScript at the bottom -->
{% block bottomJavaScript %}
{% endblock %}

Core/templates/login.html
{% extends 'base.html' %}
{% load static %}

<!-- Title of the page -->
{% block title %}
Login
{% endblock %}

<!-- Stylesheets -->
{% block styles %}
{% endblock %}

<!-- JavaScript at the top -->
{% block topJavaScript %}
{% endblock %}

<!-- Body Content -->
{% block content %}
<form action="{% url 'Core:login' %}" method="POST" id="Login-Form">
    <input type="text" name="username" id="Username" class="Input-Field" placeholder="Enter your username">
    <input type="password" name="password" id="Password" class="Input-Field" placeholder="Enter your password">
    <select name="role" id="role" class="Input-Field">
        <option value="admin">Admin</option>
        <option value="doaa">DOAA</option>
        <option value="faculty">Faculty</option>
        <option value="student">Student</option>
    </select>
    {% csrf_token %}
    <input type="submit" value="Log In">
</form>
<p>Not registered yet? <a href="{% url 'Core:createAccount' %}">Register</a></p>
{% endblock %}

<!-- JavaScript at the bottom -->
{% block bottomJavaScript %}
{% endblock %}

Core/templates/student-panel.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'CSS/student-style.css' %}">
    <title>haveASeat | Student Panel</title>
</head>
<body>
    <div class="Container">
        <div class="Left-Side-Panel">
            <form action="{% url 'Core:filterCourses' %}" method="POST" id="filterCourses">
                {% csrf_token %}
            <div class="Section-Heading">
                <p>Courses</p>
            </div>
            <div class="Section">
                <div class="Sub-Section">
                    <label for="" class="Sub-Section-Label">Program</label>
                    <div class="Input">
                        <input type="checkbox" name="B-Tech" class="Input-Field" value="B-Tech">
                        <label for="" class="Input-Label">B. Tech</label>
                    </div>
                    <div class="Input">
                        <input type="checkbox" name="M-Tech" class="Input-Field" value="M-Tech">
                        <label for="" class="Input-Label">M. Tech</label>
                    </div>
                    <div class="Input">
                        <input type="checkbox" name="PhD" class="Input-Field" value="PhD">                    
                        <label for="" class="Input-Label">PhD</label>
                    </div>
                </div>
                <div class="Sub-Section">
                    <label for="" class="Sub-Section-Label">Credits</label>
                    <div class="Input">
                        <input type="checkbox" name="cred4" class="Input-Field" value="4">
                        <label for="" class="Input-Label">4</label>
                    </div>
                    <div class="Input">
                        <input type="checkbox" name="cred2" class="Input-Field" value="2">
                        <label for="" class="Input-Label">2</label>
                    </div>
                </div>
            </div>
            <input type="submit" value="FILTER" class="Enroll-Button" style="margin-right: 20%; width: 70%;">
            </form>
            <!-- <form action="{% url 'Core:getAllCourses' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="FETCH COURSES" class="Enroll-Button" style="margin-right: 20%; width: 70%;">
            </form> -->
        </div>
        {% block content %}
        <div class="Main-Panel">
            <form action="{% url 'Core:deleteCourses' %}" method="POST" id="deleteCourses">
                {% csrf_token %}
                <div class="Panel-Results">
                    <table class="Panel-Table">
                        <tr class="Panel-Table-Row">
                            <th class="Panel-Table-Heading">S No.</th>
                            <th class="Panel-Table-Heading">Course Name</th>
                            <th class="Panel-Table-Heading">Credits</th>
                            <th class="Panel-Table-Heading">Offered To</th>
                            <!-- <th class="Panel-Table-Heading">Enroll</th> -->
                            <th class="Panel-Table-Heading">Remove</th>
                        </tr>
                        
                        {% for course in courseList %}
                        {% if course != None and course.isLive == 1 %}
                        <tr class="Panel-Table-Row">
                            <td class="Panel-Table-Heading" name="id">{{course.id}}</td>
                            <td class="Panel-Table-Heading"><a href="/{{course.courseName}}/" style="text-decoration: none; color: black">{{course.courseName}}</a></td>
                            <td class="Panel-Table-Heading">{{course.credits}}</th>
                            <td class="Panel-Table-Heading">{{course.program}}</td>
                            <td class="Panel-Table-Heading">
                                <input type="checkbox" id="courses" name="courseList" value="{{course.id}}">
                            </td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </table>
                </div>
                <!-- <input type="submit" value="Fetch Courses" class="Enroll-Button"> -->
                <input style="margin-right:10px;" type="submit" value="Delete" class="Enroll-Button">
            </form>
        </div>
        {% endblock %}
    </div>
</body>
<script src="{% static 'JavaScript/admin-script.js' %}"></script>
</html>